### ISSUE TITLE
Unread messages notification dots/badges on team icons disappear, and don't appear correctly unless you switch teams

### ISSUE THREAD

**Issue by kenyon** [mattermost/mattermost#19589]
#### Summary
Unread messages notification dots/badges on team icons disappear, and don't appear correctly unless you switch teams

#### Steps to reproduce
Be a member of multiple teams. Have new messages come in on teams other than the one you're currently viewing.

Mattermost Enterprise Edition 6.0.2 using the official Docker image. PostgreSQL database.

Problem occurs both in the web interface, and in mattermost-desktop applications, so does not seem to be specific to the client.

#### Expected behavior
New/unread message notification dots/badges on team icons/squares should always be accurate.

#### Observed behavior (that appears unintentional) 
New messages in teams that you're not currently viewing may not cause notification badges on the team squares in the sidebar. Sometimes badges appear, but they will disappear after several minutes. The only way to know whether unread messages exist on other teams is to change your view to other teams, which causes the notification badges to temporarily become accurate, until the badges disappear again.

**Comment by amyblais** [comment]
@kenyon Do you see any Mattermost server log errors from around the time the issue occurs? 
Are you able to upgrade to a more recent version, e.g. v6.3.3?

**Comment by kenyon** [comment]
Not seeing any errors in the server log related to this. I didn't realize that we were on such an old, unsupported version already, so we will upgrade and report back here. (Might take a while to get to the upgrade, though.) Thanks.

**Comment by plwalsh** [comment]
Also seeing this exact same behavior, with both the web browser and the desktop app (tray icon). Looks like my company is currently running version 5.37.6 of Mattermost Team Edition.

**Comment by account310** [comment]
docker version same issue

**Comment by amyblais** [comment]
@hmhealey @M-ZubairAhmed Would you know what other information we'd need to find out if there is a bug here?
I wasn't able to reproduce this myself. One of the reporters mentioned that they didn't see any log errors.

**Comment by hmhealey** [comment]
I'm not sure of anything specific. This sort of issue comes up occasionally, but I don't think we have a good process for debugging it since there's plenty of possible causes.

I guess the things I'd wonder from everyone would be:
1. Which server version are you running specifically? Some people have answered, but version will likely matter for the others
2. Are you running in a multi-server setup at all? That requires Enterprise Edition specifically with a license, so that wouldn't matter for just TE
3. Do you have Collapsed Reply Threads enabled on the server or for an affected user?
4. Is the websocket connected and transmitting other data? Like, do you see posts coming in in real time?

The problem is likely either that the websocket messages for unreads aren't coming through properly or that the math for unreads is incorrect which I think has been an issue with Collapsed Reply Threads in the past.

**Comment by plwalsh** [comment]
1. Server version 5.37.6 of Mattermost Team Edition
2. N/A for TE
3. I don't see the setting in my user account to enable CRTs, so I'm going to assume they're not enabled on our server.
4. All my messages appear to arrive in real-time. I haven't noticed otherwise.

Strangely, though, I only started noticing this happen after upgrading my desktop app from v4.6.2 to v5.0.4. At which point, I went to the browser version and saw the issue happening there as well. I never use the browser otherwise, so I would have no idea if the issue was happening there all along.

**Comment by hmhealey** [comment]
I'd assume it's happening in both if it's affecting the team sidebar in the app. The Desktop App is mostly a wrapper around the web app, so unless this was just affecting the tabs at the top or the Taskbar/Dock icon, then the issue is likely in the app itself.

I might come back to the websocket stuff later since I wonder if only certain requests are coming through even if posts are received in real time, but I thought of some other things we could check:
1. Do you have a lot of muted channels or channels where you've changed the notification settings from the defaults? I'm wondering if some of the math around those channels doesn't take those settings into account or handles them incorrectly
2. Would you be able to capture a short video next time this happens? Obviously, don't worry about it if you're worried about exposing sensitive information, but I'm curious if there's anything else that might show up in a video that we haven't thought to ask about

**Comment by plwalsh** [comment]
So after reading that, and revisiting my experience, it's possible that my problem is actually specific to the Desktop App. I first came to this issue page because I was also noticing that the team sidebar wasn't always showing me notification dots on teams other than the one currently selected. But I'm realizing now that I actually haven't seen that happen again since that first day.

What I do see, however, is that the Windows taskbar/system tray icon is directly influenced by which Team is currently selected. If I have new notifications in Team B, but I currently have Team A selected, the tray icon shows no notification dot. But as soon as I switch to Team B, the icon displays a dot. I can go back and forth between Team A and Team B, and the dot will appear/disappear accordingly. When I tested this in the web browser the first day, I initially thought this unexpected behavior was replicated in the browser tab favicon. So I assumed it used the same underlying logic for the system tray icon. However, now I'm seeing the favicon behave as expected; showing me a notification dot for any team, regardless of which team is selected.

So maybe I need to open a new issue in the desktop project?

And unfortunately, screen recording is not allowed on my system.

**Comment by kenyon** [comment]
The problem I originally described definitely happens in both the desktop app and web app.

Responding to @hmhealey's questions:

1. Mattermost Enterprise Edition 6.0.2 using the official Docker image. As mentioned, we need to upgrade and are planning to upgrade ASAP.
2. Not multi-server.
3. Collapsed reply threads is disabled on the server.
4. Yes posts come in real time, and I see a number (299) of "websocket conns" on the System Statistics page, so I guess websockets are working. But, going to Developer Tools in the desktop app, or web app with Firefox, and selecting WS in the Network Inspector, I'm not seeing any traffic, but not sure if that's normal.

**Comment by hmhealey** [comment]
Thanks for the responses!

I think we've identified an issue specific to the Desktop App around this. I'm not sure if that will solve everyone's issue that's being reported here, but it should hopefully help some people.

Here's the PR: https://github.com/mattermost/desktop/pull/2020. We can post back with a nightly build of that once that's out so that people can try it out

**Comment by plwalsh** [comment]
Hi @hmhealey, has a new build with the abovementioned fix been created yet? Or is there a timeline for when it will hit the public release channel? Thanks!

**Comment by hmhealey** [comment]
It won't be in a full release until 5.1 which I believe is coming next month, but it's available in nightly releases. Those can generally be found in the ~desktop-builds channel on https://community.mattermost.com.

**Comment by kenyon** [comment]
We upgraded the server to 6.5.0. No change in behavior.

**Comment by kenyon** [comment]
Using 5.1.0-nightly.20220412 commit 2bdf5428, it does look like this is fixed there.

**Comment by kenyon** [comment]
Commented too soon. I still see this happening with the nightly desktop application. New messages could be received in another team, and I won't see an indicator dot on the team until I switch teams. Doesn't always happen, seems like it happens more after a long period (like overnight) where there hasn't been activity in teams I'm not currently viewing.

**Comment by maxgorovenko** [comment]
Same issue still appears at server/webapp 7.3.0 and desktop client 5.1.1. We are moving soon to 7.5.1, hope this could be fixed

**Comment by lmoureaux** [comment]
This issue is still happening to me. It seems correlated with losing the network connection for a while (e.g. by going to sleep mode).

**Comment by flonou** [comment]
I have the same kind of issues. I usually put my computer to hibernate and use the desktop client on windows.
I often get the "badge" telling me I have unread messages or pings in the taskbar, but nothing shows on the application. I need to go through each team one by one until I find the ones where I have unread messages

**Comment by ike5** [comment]
> I often get the "badge" telling me I have unread messages or pings in the taskbar, but nothing shows on the application. I need to go through each team one by one until I find the ones where I have unread messages

This is exactly it. Though I've gone through every team to find unread messages (I only have 3 teams so it's not much) but there aren't any.

My last comment was for v7 but my company is still experiencing this issue while on v9.8.0.

**Comment by flonou** [comment]
I still have this issue regularly when my computer wakes from sleep. I got information about unread messages but no team shows anything and I have to go to them one by one.
Even after reading messages, I sometimes have the indication left that I have messages to read so it also has issues clearing correctly

**Comment by amyblais** [comment]
The fix is included in v10.2,
