### ISSUE TITLE
[Bug]: White Screen when replying to a thread

### ISSUE THREAD

**Issue by dloxterm** [mattermost/mattermost#23520]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

Ubuntu Linux 23.04 x64

### Mattermost Server Version

7.10.2

### Steps to reproduce

1. Open a direct message, or a channel
2. Try to reply to a thread, either by using Shift + Arrow up, or with the Reply Icon

### Expected behavior

I can reply normally to a thread

### Observed behavior

The Desktop App will turn completely white, and I can reload with Ctrl+R, but it will happen again and again.

After doing something else, the reply function will work again, but certainly fail again troughout the day.

### Log Output

```shell
[2023-05-26 08:23:14.147] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-05-26 08:23:14.150] [debug] DownloadsManager.saveAll
[2023-05-26 08:23:14.150] [debug] DownloadsManager.checkForDeletedFiles
[2023-05-26 08:23:14.173] [error] Log level set to: warn
[2023-05-26 08:23:14.180] [warn]  Current working directory is /home/USERNAME, changing into /opt/Mattermost
[2023-05-26 08:23:14.280] [warn]  couldn't show SERVERNAME___TAB_MESSAGING, not ready
[2023-05-26 08:23:14.283] [warn]  Failed to set new language en-US
[2023-05-26 08:23:14.284] [warn]  Failed to set new language DE
[2023-05-26 08:25:51.004] [warn]  main window closed
[2023-05-26 08:26:43.434] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-05-26 08:26:43.438] [debug] DownloadsManager.saveAll
[2023-05-26 08:26:43.439] [debug] DownloadsManager.checkForDeletedFiles
[2023-05-26 08:26:43.466] [error] Log level set to: warn
[2023-05-26 08:26:43.475] [warn]  Current working directory is /home/USERNAME, changing into /opt/Mattermost
[2023-05-26 08:26:43.587] [warn]  couldn't show SERVERNAME___TAB_MESSAGING, not ready
[2023-05-26 08:26:43.590] [warn]  Failed to set new language en-US
[2023-05-26 08:26:43.590] [warn]  Failed to set new language DE
[2023-05-26 08:31:12.545] [warn]  main window closed
[2023-05-26 08:31:14.381] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-05-26 08:31:14.385] [debug] DownloadsManager.saveAll
[2023-05-26 08:31:14.385] [debug] DownloadsManager.checkForDeletedFiles
[2023-05-26 08:31:14.412] [error] Log level set to: warn
[2023-05-26 08:31:14.420] [warn]  Current working directory is /home/USERNAME, changing into /opt/Mattermost
[2023-05-26 08:31:14.540] [warn]  couldn't show SERVERNAME___TAB_MESSAGING, not ready
[2023-05-26 08:31:14.543] [warn]  Failed to set new language en-US
[2023-05-26 08:31:14.543] [warn]  Failed to set new language DE
```

### Additional Information

I have disabled the "Collapsed Reply Threads" Option in my settings

Currently it is working again, but once it fails, I will add the output of the developer console, there are some error messages.

**Comment by dloxterm** [comment]
Finally I could reproduce it somehow, however, this also occurs during a switch of channels now as well.
I've attached the logs from the developer console (Scope: Current Server) let me know if you need else.
[mattermost-1686053855520.log](https://github.com/mattermost/mattermost/files/11664533/mattermost-1686053855520.log)

**Comment by M-ZubairAhmed** [comment]
@dloxterm thank you for attaching the log. This does seems like a bug. Does this always happens? or only sometimes

**Comment by dloxterm** [comment]
Hey @M-ZubairAhmed it happens multiple times throughout the day. Sometimes it happens very often, and I need to restart the client, sometimes I simply need to reload (Ctrl+R).

It's very difficult to reproduce, e.g. when it happens 3 times in a row, when I try to reply to a thread, but after opening the Dev Console it's gone.

**Comment by dloxterm** [comment]
Hi there, 
I've checked with some colleagues, and they all have the same issue. So far I can tell it does not depend on the operating system or if a browser or the app is used.

One colleague reported he has both the App and the Browser Tab open, and if he can't reply in the App, he can use the browser instead.

I could reproduce it now on a Thread that is in a private channel. It happened with two messages, one was edited, and the other contained a screenshot.
I've also seen that it sometimes happens when there was a reaction to one of the messages.

It seems to help to click the Reply Button on a different message than the last one. That solved it for me a few times.

Others that sometimes have the issue as well, can reply normally to the thread.

**Comment by M-ZubairAhmed** [comment]
@amyblais yes please

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53149.

**Comment by M-ZubairAhmed** [comment]
Hey @dloxterm, I discovered that when a post is absent from the Redux store but its ID is still present in other locations, the aforementioned stack trace occurs. Moreover, to trigger this issue, the "Enable Join/Leave Messages" configuration should be turned off.

Have you manually deleted a post from database anytime?

**Comment by dloxterm** [comment]
Hey @M-ZubairAhmed 

We're using Mattermost E10 at the moment, sorry, I totally forgot to mention that!

I've disabled the Join/Leave messages, yes. I will ask my colleagues who have this issue if they've also disabled the messages.

We use a managed hosting for Mattermost and can't access the database. I do not think that our hoster deleted any message from the DB since they would only do so on our request, but I try to find out.

When the error occured last time I could not see any error in the network tab, but I can keep it open again and check if I see something.

**Comment by dloxterm** [comment]
Hi @M-ZubairAhmed,
do you have any news?
It seems to happen more often if I reply to a thread where the last message has been edited. 
If I hit the reply button on earlier messages in the same thread, sometimes it works again.

**Comment by dloxterm** [comment]
Hey @M-ZubairAhmed 
I can try, however there's most of the time some confidential data that I can't give away.
In the Network Tab, there's no errors. 

However, I found a way to reproduce:
- A Thread view (bar on the right) is open from a channel or a user, lets say John Doe
- I want to open another Thread from a different User, Jane Doe
- If Jane has *edited* the last message in the thread **and** it contains an emoji now, the screen will go white, when I try to reply to the thread.

**Comment by guenjun** [comment]
An enterprise customer also reported this error.

**Comment by amyblais** [comment]
There was a note in the Jira ticket that this got fixed in v9.1 via https://github.com/mattermost/mattermost/pull/24510.

**Comment by cfi-gb** [comment]
It seems a fix has been also included in 8.1.0 via: #24537 (Cherry-pick from #24510).

**Comment by ChriFo** [comment]
Still happend for me if `Enable Join/Leave Messages` is disabled.

DevTools console:
![mm-error](https://github.com/mattermost/mattermost/assets/7130686/f77e551c-0722-4333-a0fe-3b1939c939a9)

**Comment by dloxterm** [comment]
I can still see it with 9.1.1 as well.
Also it happens in the browser now, while before it was only in the app

**Comment by dloxterm** [comment]
Hi @amyblais is it possible to re open this issue?
It's getting worse, before it happened only some times a week, now it's happening multiple times a day, most times with edited messages.

**Comment by dloxterm** [comment]
Thanks!
So, I've found out that if the last message in a thread has been edited, and I try to reply, the white screen comes up.

Reproduced it like so:

- Get a response to a thread in a channel / DM
- This message is edited 
- I open the chat and try to respond to the thread
- White Screen happens with the same error in the console as in this comment:
https://github.com/mattermost/mattermost/issues/23520#issuecomment-1787118714

![image](https://github.com/mattermost/mattermost/assets/75365794/4d992c0c-ac62-4579-b820-9cf6c1825ec7)


- Does not happen for messages that were not send in a thread, even if edited (or not that often)
- Does not happen if there is another response to the thread, that has not been edited:
![image](https://github.com/mattermost/mattermost/assets/75365794/6ed6ed34-75dc-4767-b1db-c29894ae4b8b)


I've seen it in the browser as well, but not as often.

It seems to happen less often when the Chat is already opened when the message is edited.

**Comment by marianunez** [comment]
@dloxterm can you capture your dev tool console when you see this happening again?

**Comment by dloxterm** [comment]
Hey @marianunez 
If you need a screenshot: 
![image](https://github.com/mattermost/mattermost/assets/75365794/612bdcd7-2063-4a9a-bdeb-4d0c6ebe0f36)

Or do you need something else?

**Comment by amyblais** [comment]
v9.4.2 dot release was released today with the fix, and the fix is also queued for v9.5.0.
