### ISSUE TITLE
group notifications do not work if you mention your own group

### ISSUE THREAD

**Issue by beliaev-maksim** [mattermost/mattermost#23936]
#### Summary
group notifications do not work if you mention your own group

#### Description
Sometimes we need to notify our teams, eg if you are a manager and see some thread and want to ping your firefighters, then you cannot do it, if you are part of the group.
All external people can do it

#### Steps to reproduce

1. Create a new user group
2. setup name
3. setup mention
4. invite yourself
5. open any public channel
6. mention your group

#### Expected behavior
Group mention becomes highlighted and all group members get notified

#### Observed behavior (that appears unintentional) 
Group mention is plain text, noone notified
![image](https://github.com/mattermost/mattermost/assets/51964909/ca8771c0-6d77-4111-8a84-75642ddfce93)

**Comment by amyblais** [comment]
@beliaev-maksim What Mattermost server version are you on? I wasn't able to reproduce this on latest version.

**Comment by beliaev-maksim** [comment]
@amyblais 
we use
Mattermost Version: 7.8.0

**Comment by amyblais** [comment]
@beliaev-maksim Thank you, just to confirm, would you be able to help test this on https://community.mattermost.com/ which is on the latest version to see if you can reproduce it there?

**Comment by beliaev-maksim** [comment]
@amyblais 

I created a group `@maksim-beliaev-test-not`
looks to work https://community.mattermost.com/core/pl/ec8cij9izpfe8cnz1ddri4yh8a

**Comment by amyblais** [comment]
I'm not sure why it works on the latest version but not on v7.8.0, I didn't find any tickets where this was fixed since v7.8.0. We do have various tickets open and the issue you're seeing might be related to one of these:
 - https://mattermost.atlassian.net/browse/MM-48087
 - https://mattermost.atlassian.net/browse/MM-51211
 - https://mattermost.atlassian.net/browse/MM-49995

**Comment by Pjack** [comment]
I still encounter this issue. After I create the user group, I can use it in some private channls, but not all of them. And I cannot use any user group in any public channel. I tried 20+ public channel so far. 
The mattermost version is 8.1.3 now.
