### ISSUE TITLE
After upgrading to 9.1.2, the Mattermost version does not appear in the console.

### ISSUE THREAD

**Issue by amitesh2181763** [mattermost/mattermost#25335]
#### Summary
After upgrading to 9.1.2, the Mattermost version does not appear in the console.
We are using docker image and below is the image name.
Image Name:  mattermost/mattermost-team-edition:9.1.2

#### Steps to reproduce
We are upgrading Mattermost from version 9.1.1 to 9.1.2 and facing this issue.

#### Expected behavior
When we are checking in Mattermost (Mattermost Team Edition) -->About Mattermost --> Mattermost version it is showing version like 9.1.2.

#### Observed behavior (that appears unintentional) 
When we are checking in Mattermost ((Mattermost Team Edition) -->About Mattermost --> Mattermost version it is showing CI (In place of version 9.1.2) and screen shot attached for same
<img width="369" alt="Mattermost" src="https://github.com/mattermost/mattermost/assets/136332716/ad742e00-2977-42dc-b23d-aedcc1950d22"> 

#### Possible fixes
We are not sure about this issue.

**Comment by KOliver94** [comment]
There was a similar issue earlier for version 8.0.0 that got fixed but seems like it happened again. https://github.com/mattermost/mattermost/issues/24034

**Comment by amyblais** [comment]
Our DevOps team is looking into this issue.

**Comment by cedarice** [comment]
I have the same issuse with version 9.1.2

**Comment by amyblais** [comment]
A PR to fix this has been submitted: https://github.com/mattermost/mattermost/pull/25370.

**Comment by amyblais** [comment]
A fix has been released with v9.2.2. The fix will also be applied to v9.1.x / v9.0.x / v8.1.x dot releases in the upcoming days.

**Comment by amyblais** [comment]
This is now fixed in the latest v9.1.3 / v9.0.4 / v8.1.6 dot releases.

**Comment by felibb** [comment]
@amyblais just installed 8.1.6, and still see `Build number is not in semver format` in my log.

**Comment by amyblais** [comment]
> just installed 8.1.6, and still see Build number is not in semver format in my log.

cc @toninis would you know why there is an error in the log?

**Comment by toninis** [comment]
Build number won't be in semver format from now on . It's the number of the actual build on Github 😄

**Comment by felibb** [comment]
Dang, I feel like I commented on the wrong issue here, apologies. Yet that message appears quite a few times. Should I open a case/a new issue?

**Comment by toninis** [comment]
@felibb Thanks for reporting this . We will create a ticket internally . You can also open a ticket to track progress 👍🏼

**Comment by toninis** [comment]
We need to change the code [here](https://github.com/mattermost/mattermost/blob/master/server/channels/app/product_notices.go#L96)
