### ISSUE TITLE
[Bug]: Chat stopps auto scrolling for new messages

### ISSUE THREAD

**Issue by jameskitt616** [mattermost/mattermost#33536]
### Before you file a bug report

- [x] I have checked the [issue tracker](https://github.com/mattermost/mattermost/issues) and have not found an issue that matches the one I'm filing.
- [x] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [x] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.uservoice.com/forums/306457-general/.
- [x] This issue reproduces on one of the [currently supported server versions](https://docs.mattermost.com/about/mattermost-server-releases.html#latest-releases).
- [x] I have read the [contribution guidelines](https://github.com/mattermost/mattermost/blob/master/CONTRIBUTING.md) and the [Mattermost Handbook Contribution Guidelines](https://handbook.mattermost.com/contributors/contributors/guidelines/contribution-guidelines).

### Mattermost Server Version

10.10.1

### Operating System

Fedora Linux 42

### Steps to reproduce

Open a DM with another Person, have them spam you with messages, eventually after some seconds it will stop scrolling down for the new messages. This behaviour probably changed since Server Version upgrade to 10.10.1

### Expected behavior

It should keep scrolling for new Messages

### Observed behavior

Open a DM with another Person, have them spam you with messages, eventually after some seconds it will stop scrolling down for the new messages.

### Log Output

```shell

```

**Comment by mvazquez** [comment]
For me this happends on channels too since the last server update, and you can't know that there are new mesasges, before this update the app showed a message telling that there were new messages, but now it does not show anything, and changing the advanced option about scrolling to the last message automatically does not change anything either

**Comment by Grucqq** [comment]
got same problem here as described above - mattermost 10.10.1 / postgres 13 / almalinux 9

**Comment by scmanjarrez** [comment]
I was going crazy, this happens to me too. It's really annoying. Mattermost 10.11.0, desktop and web.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-64914.

**Comment by Dulanic** [comment]
Noticed it quite a bit this morning.

**Comment by Dulanic** [comment]
Feels like it happens when it's X amount of rows in Y amount time. I do not know the values are though, it happens in channels also.

**Comment by tkcl81** [comment]
Facing the same problem with MM 10.10.1 and MM Desktop client 5.12.1 on macOS.

**Comment by YANANEER** [comment]
Same problem with 10.10.1 and 10.11.0 rc1

**Comment by T20A02** [comment]
I am also experiencing this issue with an updated 10.10.1 install.

**Comment by martina3visiol** [comment]
Same here server version 10.10.1 client OSX 5.12.1

**Comment by oscar-bsmart** [comment]
Same problem with 10.10.1

**Comment by ElenaMalvica** [comment]
same here, desktop version 5.12.1 on windows

**Comment by stefanoalba** [comment]
Same problem with desktop version 5.12.1 on MAC

**Comment by fishgit** [comment]
I think we can stop reporting with "Same here" now. 

This bug is known and according to https://mattermost.atlassian.net/browse/MM-64957 it is fixed in the releases 10.11 and 10.10.2 that will be published soon (august).

**Comment by netpok** [comment]
For v10.10.1 we patched it with:
```
sed -i -e 's/padding:.2em 0;/padding: 0 0 .2em;/g' /<path to mattermost dir>/mattermost/client/6838.ffa1861d9e04f0518196.css
```

Without using sed:
- Find the file: `6838.ffa1861d9e04f0518196.css`
- Replace `padding:.2em 0;` with `padding: 0 0 .2em;`
- Profit

This works on the web version, I don't use the desktop client so not sure about that.

**Comment by mimrock** [comment]
I'm running v10.10.1 (Free Edition) and I still have this exact issue on Firefox (142.0, linux). Haven't tried with other browsers or the desktop client yet.

**Comment by em-ex** [comment]
Sorry for posting in a closed issue, but I'm having the auto-scroll not working issue with Mattermost server v11.0.4 in its web client (using Firefox) since the recent update. I'd gladly apply @netpok's monkeypatch and forget about it till next update but the file names are obviously different, and they don't mention any class names.
