### ISSUE TITLE
Reorganize tagging of the mattermost-push-proxy container

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost#9459]
#### Summary
From https://github.com/mattermost/mattermost-docker/issues/303:
The [mattermost-push-proxy container on Docker Hub](https://hub.docker.com/r/mattermost/mattermost-push-proxy/) does not contain a `latest` tag. There are also no tags for major releases.
If you want to use the container, you have to track the upstream tags and change then manually on every new release.

Furthermore, the [releases page](https://github.com/mattermost/mattermost-push-proxy/releases) for the push proxy shows `4.4.10` as latest version, but the tag with the highest version on [Docker Hub](https://hub.docker.com/r/mattermost/mattermost-push-proxy/tags/) is `5.2.1` (`4.4.10` does not exist).

#### Steps to reproduce
Run `docker pull mattermost/mattermost-push-proxy`

#### Expected behavior
Should pull the latest version of the push proxy container.

#### Observed behavior (that appears unintentional) 
`Error response from daemon: manifest for mattermost/mattermost-push-proxy:latest not found`

#### Possible fixes
Set-up [automated builds](https://docs.docker.com/docker-cloud/builds/automated-build/) as it's already the case with the [mattermost-prod-app](https://github.com/mattermost/mattermost-docker) repo and tag new releases.

**Comment by amyblais** [comment]
Hi @J0WI, thank you for reporting this.

I created a Jira ticket for the Issues here: https://mattermost.atlassian.net/browse/MM-12316.

**Comment by jaydeland** [comment]
I am looking at this under:
https://mattermost.atlassian.net/browse/MM-19710

**Comment by jaydeland** [comment]
I don’t yet have access to the main repo so I have completed number 1 and 2 on a fork.
It appears that number 3 is no longer an issue.
https://hub.docker.com/r/jaydeland/mattermost-push-proxy/tags

I have also migrated Docker to alpine:3.10.1 (since this is the latest version).
https://github.com/jaydeland/mattermost-push-proxy

CircleCI:
https://circleci.com/gh/jaydeland/mattermost-push-proxy

**Comment by hanzei** [comment]
Is this fixed with https://github.com/mattermost/mattermost-push-proxy/pull/55?

**Comment by J0WI** [comment]
I get `/entrypoint.sh: line 23: mattermost-push-proxy: not found` with current latest.
Tags for major releases like in https://github.com/mattermost/mattermost-docker/issues/369 are still missing.

**Comment by amyblais** [comment]
I'll close this as this is an old issue. Feel free to create a new issue if there are any outstanding bugs,
